# Generated by Django 5.2.6 on 2025-09-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconnection',
            old_name='to_user',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='userconnection',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together={('sender', 'reciever')},
        ),
        migrations.AddField(
            model_name='userconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
