# Generated by Django 5.2.6 on 2025-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_to_user_userconnection_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganiserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
