# Generated by Django 5.2.6 on 2025-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('mainusers', '0001_initial'),
        ('users', '0004_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqrcode',
            name='qr_code_image',
            field=models.ImageField(upload_to='qr_codes/'),
        ),
        migrations.AlterUniqueTogether(
            name='eventenrollment',
            unique_together={('user', 'event')},
        ),
    ]
